root: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - "plugin:@typescript-eslint/recommended"
  - eslint:recommended
  - react-app

rules:
  no-await-in-loop: 1
  no-extra-parens:
    - warn
    - functions
  no-template-curly-in-string: 2

  accessor-pairs: 2
  array-callback-return: 2
  block-scoped-var: 2
  class-methods-use-this: 2
  complexity: 0
  consistent-return: 2
  curly: 0
  default-case: 2
  dot-location: 0
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  max-classes-per-file: 2
  no-alert: 1
  no-caller: 2
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-implicit-coercion: 0
  no-implicit-globals: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-magic-numbers: 0
  no-multi-spaces: 2
  no-multi-str: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-proto: 2
  no-restricted-properties: 0
  no-return-assign: 2
  no-return-await: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments: 1
  prefer-named-capture-group: 0
  prefer-promise-reject-errors: 2
  radix: 2
  require-await: 2
  require-unicode-regexp: 0
  vars-on-top: 0
  wrap-iife: 2
  yoda: 2

  strict: 0

  init-declarations: 1
  no-label-var: 2
  no-restricted-globals: 0

  no-shadow: 0
  '@typescript-eslint/no-shadow':
    - error

  no-undef-init: 2
  no-undefined: 0
  no-use-before-define: 0

  no-buffer-constructor: 2
  no-mixed-requires: 2
  no-new-require: 2
  no-sync: 2

  array-bracket-newline: 0
  array-bracket-spacing: 2
  array-element-newline: 0
  block-spacing: 2
  brace-style: 2
  camelcase: 0
  capitalized-comments: 0
  comma-dangle:
    - warn
    - always-multiline
  comma-spacing: 1
  comma-style: 2
  computed-property-spacing: 0
  consistent-this: 2
  eol-last: 0
  func-call-spacing: 2
  func-name-matching: 2
  func-names: 2
  func-style: 0
  function-paren-newline: 0
  id-blacklist: 0
  id-length: 0
  id-match: 0
  implicit-arrow-linebreak: 0
  indent: 0
  jsx-quotes: 0
  key-spacing: 2
  keyword-spacing: 1
  line-comment-position: 0
  linebreak-style: 0
  lines-around-comment: 0
  lines-between-class-members: 0
  max-depth: 0
  max-len: 0
  max-lines: 0
  max-lines-per-function: 0
  max-nested-callbacks: 2
  max-params: 0
  max-statements: 0
  max-statements-per-line: 2
  multiline-comment-style: 0
  multiline-ternary:
    - warn
    - always-multiline
  new-cap: 2
  new-parens: 2
  newline-per-chained-call: 2
  no-array-constructor: 2
  no-bitwise: 0
  no-continue: 0
  no-inline-comments: 0
  no-lonely-if: 2
  no-mixed-operators: 2
  no-mixed-spaces-and-tabs: 2
  no-multi-assign: 2
  no-multiple-empty-lines: 1
  no-negated-condition: 0
  no-nested-ternary: 0
  no-new-object: 2
  no-plusplus: 0
  no-restricted-syntax: 0
  no-tabs: 2
  no-ternary: 0
  no-trailing-spaces: 1
  no-underscore-dangle: 0
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  object-curly-spacing: 0
  object-property-newline:
    - warn
    - allowAllPropertiesOnSameLine: true
  one-var: 0
  one-var-declaration-per-line: 2
  operator-assignment: 2
  operator-linebreak:
    - warn
    - before
  padded-blocks: 0
  padding-line-between-statements: 0
  prefer-object-spread: 2
  quote-props: 0
  quotes: 0
  semi: 0
  semi-spacing: 0
  semi-style: 0
  sort-keys: 1
  sort-vars: 1
  space-before-blocks: 1
  space-before-function-paren: 0
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: 2
  switch-colon-spacing: 2
  template-tag-spacing: 2
  unicode-bom: 2
  wrap-regex: 2

  arrow-body-style: 0
  arrow-parens: 0
  arrow-spacing: 2
  generator-star-spacing: 2
  no-confusing-arrow: 2
  no-duplicate-imports: 2
  no-restricted-imports: 0
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-destructuring: 0
  prefer-numeric-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  rest-spread-spacing: 2
  sort-imports: 1
  symbol-description: 2
  template-curly-spacing: 2
  yield-star-spacing: 2