; Generated by Coffee-AHK/0.0.17
global __ci_genshin__ := Func("genshin_63")
if (A_IsAdmin != true) {
  Run *RunAs "%A_ScriptFullPath%"
  ExitApp
}
#KeyHistory, 0
#MaxThreads, 20
#NoEnv
#Persistent
#SingleInstance, Force
#UseHook, On

CoordMode, Mouse, Client
CoordMode, Pixel, Client
CoordMode, ToolTip, Client
SendMode, Event
SetBatchLines, 100ms
SetKeyDelay, 0, 50
SetMouseDelay, 0, 50
StringCaseSense, On
; Generated by Coffee-AHK/0.0.17
global __ci_jsShim__ := Func("jsShim_53")
global $ := {}
$.beep := Func("jsShim_52")
$.blockInput := Func("jsShim_51")
$.click := Func("jsShim_50")
global __index_debounce__ := 0
global __timer_debounce__ := {}
$.debounce := Func("jsShim_49")
$.delay := Func("jsShim_47")
$.exit := Func("jsShim_46")
$.findColor := Func("jsShim_45")
$.findImage := Func("jsShim_44")
$.formatHotkey := Func("jsShim_43")
$.getColor := Func("jsShim_42")
$.getPosition := Func("jsShim_41")
$.getState := Func("jsShim_40")
$.i := Func("jsShim_39")
$.includes := Func("jsShim_38")
$.info := Func("jsShim_37")
$.length := Func("jsShim_36")
$.move := Func("jsShim_35")
$.now := Func("jsShim_34")
$.off := Func("jsShim_33")
$.on := Func("jsShim_32")
$.open := Func("jsShim_31")
$.play := Func("jsShim_30")
$.press := Func("jsShim_29")
$.push := Func("jsShim_28")
$.random := Func("jsShim_27")
$.reload := Func("jsShim_26")
$.replace := Func("jsShim_25")
$.reverse := Func("jsShim_24")
$.setFixed := Func("jsShim_23")
$.sleep := Func("jsShim_22")
$.split := Func("jsShim_21")
$.suspend := Func("jsShim_20")
global __index_throttle__ := 0
global __timer_throttle__ := {}
global __ts_throttle__ := {}
$.throttle := Func("jsShim_19")
$.toLowerCase := Func("jsShim_16")
$.toString := Func("jsShim_15")
$.toUpperCase := Func("jsShim_14")
$.trim := Func("jsShim_13")
$.trimEnd := Func("jsShim_12")
$.trimStart := Func("jsShim_11")
$.type := Func("jsShim_10")
global alert := Func("jsShim_9")
global clearInterval := Func("jsShim_8")
global clearTimeout := Func("jsShim_7")
global Math := {abs: Func("jsShim_6"), ceil: Func("jsShim_5"), floor: Func("jsShim_4"), round: Func("jsShim_3")}
global setInterval := Func("jsShim_2")
global setTimeout := Func("jsShim_1")
jsShim_1(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if (time <= 0) {
    time := 1
  }
  SetTimer, % callback, % 0 - time
  return callback
}
jsShim_2(callback, time) {
  if (($.type.Call(callback)) == "function") {
    callback := callback.Bind()
  }
  __type__ := $.type.Call(time)
  if !(__type__ == "number") {
    throw Exception("setTimeout: invalid time type '" . (__type__) . "'")
  }
  if !(time > 0) {
    throw Exception("setTimeout: invalid time value '" . (time) . "'")
  }
  SetTimer, % callback, % time
  return callback
}
jsShim_3(n) {
  return Round(n)
}
jsShim_4(n) {
  return Floor(n)
}
jsShim_5(n) {
  return Ceil(n)
}
jsShim_6(n) {
  return Abs(n)
}
jsShim_7(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
jsShim_8(callback) {
  if !(callback) {
    return
  }
  SetTimer, % callback, Delete
}
jsShim_9(message := "") {
  __msg__ := $.toString.Call(message)
  MsgBox, % __msg__
}
jsShim_10(input) {
  if input is Number
    return "number"
  if (IsFunc(input)) {
    return "function"
  }
  if (IsObject(input)) {
    if (input.Count() == input.Length()) {
      return "array"
    }
    return "object"
  }
  return "string"
}
jsShim_11(input, omitting := " `t") {
  return LTrim(input, omitting)
}
jsShim_12(input, omitting := " `t") {
  return RTrim(input, omitting)
}
jsShim_13(input, omitting := " `t") {
  return Trim(input, omitting)
}
jsShim_14(input) {
  StringUpper, __result__, input
  return __result__
}
jsShim_15(input) {
  __type__ := $.type.Call(input)
  if (__type__ == "array") {
    __result__ := ""
    for __index_for__, key in input {
      __result__ := "" . (__result__) . ", " . ($.toString.Call(key)) . ""
    }
    return "[" . ($.trim.Call(__result__, " ,")) . "]"
  } else if (__type__ == "object") {
    __result__ := ""
    for key, value in input {
      __result__ := "" . (__result__) . ", " . (key) . ": " . ($.toString.Call(value)) . ""
    }
    return "{" . ($.trim.Call(__result__, " ,")) . "}"
  }
  return input
}
jsShim_16(input) {
  StringLower, __result__, input
  return __result__
}
jsShim_17(index, callback) {
  callback.Call()
  __ts_throttle__[__ci_jsShim__.Call(index)] := $.now.Call()
}
jsShim_18(index, time, callback) {
  clearTimeout.Call(__timer_throttle__[__ci_jsShim__.Call(index)])
  __timer_throttle__[__ci_jsShim__.Call(index)] := setTimeout.Call(Func("jsShim_17").Bind(index, callback), __ts_throttle__[__ci_jsShim__.Call(index)] - $.now.Call() + time)
}
jsShim_19(time, callback) {
  __index_throttle__++
  __ts_throttle__[__ci_jsShim__.Call(__index_throttle__)] := 0
  return Func("jsShim_18").Bind(__index_throttle__, time, callback)
}
jsShim_20(isSuspended := "Toggle") {
  if (isSuspended != "Toggle") {
    if (isSuspended) {
      isSuspended := "On"
    } else {
      isSuspended := "Off"
    }
  }
  Suspend, % isSuspended
}
jsShim_21(input, delimiter) {
  return StrSplit(input, delimiter)
}
jsShim_22(time) {
  Sleep, % time
}
jsShim_23(isFixed := "Toggle") {
  if (isFixed != "Toggle") {
    if (isFixed) {
      isFixed := "On"
    } else {
      isFixed := "Off"
    }
  }
  Winset AlwaysOnTop, % isFixed, A
}
jsShim_24(input) {
  __type__ := $.type.Call(input)
  if !(__type__ == "array") {
    throw Exception("$.reverse: invalid type '" . (__type__) . "'")
  }
  __len__ := $.length.Call(input)
  __output__ := []
  for i, key in input {
    i := i - 1
    __output__[__ci_jsShim__.Call(__len__ - 1 - i)] := key
  }
  return __output__
}
jsShim_25(input, searchment, replacement, limit := -1) {
  return StrReplace(input, searchment, replacement, limit)
}
jsShim_26() {
  Reload
}
jsShim_27(min := 0, max := 1) {
  Random, __result__, min, max
  return __result__
}
jsShim_28(list, item) {
  list.Push(item)
  return list
}
jsShim_29(listInput*) {
  if !($.length.Call(listInput)) {
    throw Exception("$.press: invalid key")
  }
  __listKey__ := []
  for __index_for__, input in listInput {
    __input__ := $.toLowerCase.Call(input)
    __input__ := $.replace.Call(__input__, " ", "")
    __input__ := $.replace.Call(__input__, "-", "")
    __list__ := $.split.Call(__input__, "+")
    for __index_for__, it in __list__ {
      __listKey__.Push(it)
    }
  }
  __listResult__ := []
  __len__ := $.length.Call(__listKey__)
  for i, key in __listKey__ {
    i := i - 1
    if (i == __len__ - 1) {
      __listResult__[__ci_jsShim__.Call(i)] := $.split.Call(key, ":")
      continue
    }
    if ($.includes.Call(key, ":")) {
      __listResult__[__ci_jsShim__.Call(i)] := $.split.Call(key, ":")
      __listResult__[__ci_jsShim__.Call((__len__ - 1) * 2 - i)] := $.split.Call(key, ":")
    } else {
      __listResult__[__ci_jsShim__.Call(i)] := [key, "down"]
      __listResult__[__ci_jsShim__.Call((__len__ - 1) * 2 - i)] := [key, "up"]
    }
  }
  for i, it in __listResult__ {
    i := i - 1
    if (it[1] == "win") {
      it[1] := "lwin"
    }
    __listResult__[__ci_jsShim__.Call(i)] := $.trim.Call("" . (it[1]) . " " . (it[2]) . "")
  }
  __output__ := ""
  for __index_for__, it in __listResult__ {
    __output__ := "" . (__output__) . "{" . (it) . "}"
  }
  Send, % __output__
}
jsShim_30(filename) {
  SoundPlay, % filename
}
jsShim_31(source) {
  Run, % source
}
jsShim_32(key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, On
}
jsShim_33(key, callback) {
  key := $.formatHotkey.Call(key)
  Hotkey, % key, % callback, Off
}
jsShim_34() {
  return A_TickCount
}
jsShim_35(point := "", speed := 0) {
  if !(point) {
    throw Exception("$.move: invalid point")
  }
  MouseMove, point[1], point[2], speed
}
jsShim_36(input) {
  __type__ := $.type.Call(input)
  switch __type__ {
    case "array": {
      return input.Length()
    }
    case "object": {
      return input.Count()
    }
    case "string": {
      return StrLen(input)
    }
    default: {
      throw Exception("$.length: invalid type '" . (__type__) . "'")
    }
  }
}
jsShim_37(message, point := "") {
  if !(message) {
    return message
  }
  if !(point) {
    point := $.getPosition.Call()
  }
  __msg__ := $.toString.Call(message)
  ToolTip, % __msg__, % point[1], % point[2]
  return message
}
jsShim_38(input, needle) {
  __type__ := $.type.Call(input)
  if (__type__ == "string" || __type__ == "number") {
    return (InStr(input, needle)) > 0
  }
  if (__type__ == "array") {
    for __index_for__, it in input {
      if (it == needle) {
        return true
      }
    }
    return false
  }
  throw Exception("$.includes: invalid type '" . (__type__) . "'")
}
jsShim_39(message) {
  $.info.Call("[" . ($.now.Call()) . "] " . ($.toString.Call(message)) . "", [0, 0])
  return message
}
jsShim_40(key) {
  return GetKeyState(key, "P")
}
jsShim_41() {
  MouseGetPos, __x__, __y__
  return [__x__, __y__]
}
jsShim_42(point := "") {
  if !(point) {
    point := $.getPosition.Call()
  }
  PixelGetColor, __result__, % point[1], % point[2], RGB
  return __result__
}
jsShim_43(key) {
  __listkey__ := []
  __key__ := $.toLowerCase.Call(key)
  __key__ := $.replace.Call(__key__, " ", "")
  __key__ := $.replace.Call(__key__, "-", "")
  _list := $.split.Call(__key__, "+")
  for __index_for__, it in _list {
    __listkey__.Push(it)
  }
  __isAlt__ := false
  __isCtrl__ := false
  __isShift__ := false
  __isWin__ := false
  __listResult__ := []
  for __index_for__, key in __listkey__ {
    if (key == "alt") {
      __isAlt__ := true
      continue
    }
    if (key == "ctrl") {
      __isCtrl__ := true
      continue
    }
    if (key == "shift") {
      __isShift__ := true
      continue
    }
    if (key == "win") {
      __isWin__ := true
      continue
    }
    __listResult__.Push(key)
  }
  __prefix__ := ""
  if (__isAlt__) {
    __prefix__ := "" . (__prefix__) . "!"
  }
  if (__isCtrl__) {
    __prefix__ := "" . (__prefix__) . "^"
  }
  if (__isShift__) {
    __prefix__ := "" . (__prefix__) . "+"
  }
  if (__isWin__) {
    __prefix__ := "" . (__prefix__) . "#"
  }
  __result__ := ""
  for __index_for__, it in __listResult__ {
    __result__ := "" . (__result__) . " & " . (it) . ""
  }
  return $.replace.Call("" . (__prefix__) . "" . ($.trim.Call(__result__, " &")) . "", ":", " ")
}
jsShim_44(source, start := "", end := "") {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  ImageSearch __x__, __y__, start[1], start[2], end[1], end[2], % A_ScriptDir . "\\\" . source
  return [__x__, __y__]
}
jsShim_45(color, start := "", end := "", variation := 0) {
  if !(start) {
    start := [0, 0]
  }
  if !(end) {
    end := [A_ScreenWidth, A_ScreenHeight]
  }
  PixelSearch __x__, __y__, start[1], start[2], end[1], end[2], color, variation, Fast RGB
  return [__x__, __y__]
}
jsShim_46() {
  ExitApp
}
jsShim_47(time, callback) {
  __timer__ := setTimeout.Call(callback, time)
  return __timer__
}
jsShim_48(index, time, callback) {
  clearTimeout.Call(__timer_debounce__[__ci_jsShim__.Call(index)])
  __timer_debounce__[__ci_jsShim__.Call(index)] := setTimeout.Call(callback, time)
}
jsShim_49(time, callback) {
  __index_debounce__++
  return Func("jsShim_48").Bind(__index_debounce__, time, callback)
}
jsShim_50(key := "left") {
  key := $.replace.Call(key, "-", "")
  key := $.replace.Call(key, ":", " ")
  Click, % key
}
jsShim_51(block) {
  if (block) {
    BlockInput, On
    return
  }
  BlockInput, Off
}
jsShim_52() {
  SoundBeep
}
jsShim_53(input) {
  if input is Number
    return input + 1
  return input
}
global state := {}
global timer := {}
global ts := {}
class ClientX {
  height := 0
  name := "YuanShen.exe"
  state := {isSuspend: false}
  width := 0
  check := Func("genshin_62").Bind(this)
  close := Func("genshin_61").Bind(this)
  getSize := Func("genshin_60").Bind(this)
  isActive := Func("genshin_59").Bind(this)
  isInside := Func("genshin_58").Bind(this)
  reset := Func("genshin_57").Bind(this)
  resetKey := Func("genshin_56").Bind(this)
  resetTimer := Func("genshin_55").Bind(this)
  suspend := Func("genshin_54").Bind(this)
  setPriority := Func("genshin_53").Bind(this)
  watch := Func("genshin_52").Bind(this)
}
class ConfigX {
  data := {character: [""]}
  source := "config.ini"
  __New() {
    for __index_for__, key in ["autoESkill", "easySkillTimer", "fastPaimonMenu", "fastPick", "improvedAttack", "improvedElementalVision", "improvedJump", "improvedSprint"] {
      this.data[__ci_genshin__.Call(key)] := this.read.Call("feature/enable" . (key) . "", 1)
    }
    for __index_for__, n in [1, 2, 3, 4] {
      $.push.Call(this.data.character, this.read.Call("character/" . (n) . "", ""))
    }
  }
  read := Func("genshin_51").Bind(this)
}
timer.countDown := ""
global countDown := Func("genshin_50")
class PaimonX {
  color := [0xFFFFFF, 0xECE5D8, 0x3B4255]
  key := ["f1", "f2", "f3", "f4", "f5", "b", "c", "j", "m"]
  state := {current: "", isVisible: false}
  ts := {check: 0}
  bindEvent := Func("genshin_49").Bind(this)
  checkVisibility := Func("genshin_45").Bind(this)
  findColor := Func("genshin_44").Bind(this)
  resetKey := Func("genshin_43").Bind(this)
}
global combo := Func("genshin_42").Call()
global klee := Func("genshin_39").Call()
global tactic := {combo: combo, klee: klee}
timer.tactic := ""
state.isAttacking := false
global setTacticDelay := Func("genshin_32")
global startAttack := Func("genshin_30")
global stopAttack := Func("genshin_29")
state.isDashing := false
timer.dash := ""
ts.dash := 0
global dash := Func("genshin_28")
global startDash := Func("genshin_27")
global stopDash := Func("genshin_26")
state.isJumping := false
timer.jump := ""
global jump := Func("genshin_25")
global startJump := Func("genshin_23")
global stopJump := Func("genshin_22")
global isMoving := Func("genshin_21")
global pauseMove := Func("genshin_20")
global resumeMove := Func("genshin_19")
state.isPicking := false
timer.pick := ""
global pick := Func("genshin_18")
global startPick := Func("genshin_17")
global stopPick := Func("genshin_16")
state.character := 0
state.isLongPressing := false
state.isToggleLocked := false
timer.toggle := ""
global startToggle := Func("genshin_15")
global stopToggle := Func("genshin_13")
state.isViewing := false
timer.view := ""
global toggleView := Func("genshin_12")
global view := Func("genshin_11")
global config := new ConfigX()
global client := new ClientX()
client.watch.Call()
global paimon := new PaimonX()
$.on.Call("alt + f4", Func("genshin_9"))
$.on.Call("ctrl + f5", Func("genshin_8"))
for __index_for__, key in ["1", "2", "3", "4", "5"] {
  $.on.Call(key, Func("genshin_7").Bind(key))
  $.on.Call("" . (key) . ":up", Func("genshin_6").Bind(key))
}
if (config.data.easySkillTimer) {
  $.on.Call("e", Func("genshin_5"))
  $.on.Call("e:up", Func("genshin_4"))
}
if (config.data.fastPaimonMenu) {
  paimon.bindEvent.Call()
}
if (config.data.fastPick) {
  $.on.Call("f", startPick)
  $.on.Call("f:up", stopPick)
}
if (config.data.improvedAttack) {
  $.on.Call("l-button", startAttack)
  $.on.Call("l-button:up", stopAttack)
}
if (config.data.improvedElementalVision) {
  $.on.Call("m-button", toggleView)
}
if (config.data.improvedJump) {
  $.on.Call("space", startJump)
  $.on.Call("space:up", stopJump)
  $.on.Call("x", Func("genshin_3"))
}
$.on.Call("r-button", startDash)
$.on.Call("r-button:up", stopDash)
if (config.data.improvedSprint) {
  $.on.Call("w", Func("genshin_2"))
  $.on.Call("w:up", Func("genshin_1"))
}
genshin_1() {
  if (state.isDashing) {
    return
  }
  $.press.Call("w:up")
}
genshin_2() {
  $.press.Call("w:down")
}
genshin_3() {
  $.press.Call("x")
  $.press.Call("space")
}
genshin_4() {
  $.press.Call("e:up")
  countDown.Call(5000)
}
genshin_5() {
  $.press.Call("e:down")
}
genshin_6(key) {
  stopToggle.Call(key)
}
genshin_7(key) {
  startToggle.Call(key)
}
genshin_8() {
  $.beep.Call()
  client.reset.Call()
  $.reload.Call()
}
genshin_9() {
  $.beep.Call()
  client.reset.Call()
  $.exit.Call()
}
genshin_10() {
  $.click.Call("middle:up")
}
genshin_11() {
  $.click.Call("middle:down")
  setTimeout.Call(Func("genshin_10"), 2500)
}
genshin_12() {
  clearInterval.Call(timer.view)
  state.isViewing := !state.isViewing
  $.click.Call("middle:up")
  if !(state.isViewing) {
    return
  }
  timer.view := setInterval.Call(view, 3000)
  view.Call()
}
genshin_13(key) {
  $.press.Call("" . (key) . ":up")
  if !(config.data.autoESkill) {
    return
  }
  state.isToggleLocked := false
  if !(state.isLongPressing) {
    return
  }
  state.isLongPressing := false
  $.press.Call("e:up")
  countDown.Call(10000)
}
genshin_14(key) {
  $.blockInput.Call(true)
  pauseMove.Call()
  client.resetKey.Call()
  if ($.getState.Call(key)) {
    state.isLongPressing := true
    $.press.Call("e:down")
  } else {
    $.press.Call("e")
    countDown.Call(5000)
  }
  resumeMove.Call()
  $.blockInput.Call(false)
}
genshin_15(key) {
  $.press.Call("" . (key) . ":down")
  state.character := key
  if !(config.data.autoESkill) {
    return
  }
  if (state.isToggleLocked) {
    return
  }
  state.isToggleLocked := true
  delay := 200
  diff := $.now.Call() - ts.dash
  if (diff > 200 && diff < 600) {
    delay := 600 - diff
  }
  clearTimeout.Call(timer.toggle)
  timer.toggle := $.delay.Call(delay, Func("genshin_14").Bind(key))
}
genshin_16() {
  if !(state.isPicking) {
    return
  }
  state.isPicking := false
  clearInterval.Call(timer.pick)
}
genshin_17() {
  if (state.isPicking) {
    return
  }
  state.isPicking := true
  clearInterval.Call(timer.pick)
  timer.pick := setInterval.Call(pick, 100)
  pick.Call()
}
genshin_18() {
  $.press.Call("f")
  $.click.Call("wheel-down")
}
genshin_19() {
  for __index_for__, key in ["w", "a", "s", "d"] {
    if ($.getState.Call(key)) {
      $.press.Call("" . (key) . ":down")
    }
  }
}
genshin_20() {
  for __index_for__, key in ["w", "a", "s", "d"] {
    if ($.getState.Call(key)) {
      $.press.Call("" . (key) . ":up")
    }
  }
}
genshin_21() {
  for __index_for__, key in ["w", "a", "s", "d"] {
    if ($.getState.Call(key)) {
      return key
    }
  }
  return false
}
genshin_22() {
  if !(state.isJumping) {
    return
  }
  state.isJumping := false
  clearInterval.Call(timer.jump)
}
genshin_23() {
  if (state.isJumping) {
    return
  }
  state.isJumping := true
  clearInterval.Call(timer.jump)
  timer.jump := setInterval.Call(jump, 100)
  jump.Call()
}
genshin_24() {
  $.press.Call("space")
}
genshin_25() {
  $.press.Call("space")
  $.delay.Call(50, Func("genshin_24"))
}
genshin_26() {
  ts.dash := $.now.Call()
  if !(config.data.improvedSprint) {
    $.click.Call("right:up")
    return
  }
  if !(state.isDashing) {
    return
  }
  state.isDashing := false
  clearInterval.Call(timer.dash)
  key := isMoving.Call()
  if !(key) {
    $.press.Call("w:up")
  } else if (key != "w") {
    $.press.Call("w:up")
  }
}
genshin_27() {
  ts.dash := $.now.Call() + 500
  if !(config.data.improvedSprint) {
    $.click.Call("right:down")
    return
  }
  if (state.isDashing) {
    return
  }
  state.isDashing := true
  clearInterval.Call(timer.dash)
  timer.dash := setInterval.Call(dash, 1300)
  dash.Call()
}
genshin_28() {
  key := isMoving.Call()
  if !(key) {
    $.press.Call("w:down")
  } else if (key != "w") {
    $.press.Call("w:up")
  }
  $.click.Call("right")
}
genshin_29() {
  state.isAttacking := false
  paimon.checkVisibility.Call()
  if (paimon.state.isVisible) {
    $.click.Call("left:up")
    return
  }
}
genshin_30() {
  paimon.checkVisibility.Call()
  if (paimon.state.isVisible) {
    $.click.Call("left:down")
    return
  }
  if (state.isAttacking) {
    return
  }
  state.isAttacking := true
  key := config.data.character[__ci_genshin__.Call(state.character)]
  if !(key) {
    key := "Combo"
  }
  if (tactic[__ci_genshin__.Call(key)]) {
    tactic[__ci_genshin__.Call(key)].attack.Call()
  }
}
genshin_31(callback) {
  if !(state.isAttacking) {
    return
  }
  callback.Call()
}
genshin_32(delay, callback) {
  clearTimeout.Call(timer.tactic)
  timer.tactic := $.delay.Call(delay, Func("genshin_31").Bind(callback))
}
genshin_33(module) {
  $.press.Call("w")
  setTacticDelay.Call(50, module.attack)
}
genshin_34(module) {
  $.click.Call("left:up")
  setTacticDelay.Call(850, Func("genshin_33").Bind(module))
}
genshin_35(module) {
  $.click.Call("left:down")
  setTacticDelay.Call(250, Func("genshin_34").Bind(module))
}
genshin_36(module) {
  $.press.Call("w")
  setTacticDelay.Call(50, module.attack)
}
genshin_37(module) {
  $.click.Call("left")
  setTacticDelay.Call(550, Func("genshin_36").Bind(module))
}
genshin_38(module) {
  if ($.now.Call() - module.ts >= 10000) {
    module.count := 0
  }
  module.ts := $.now.Call()
  if !(module.count >= 2) {
    module.count++
    module.attackA.Call()
  } else {
    module.count := 0
    module.attackB.Call()
  }
}
genshin_39() {
  module := {}
  module.count := 0
  module.ts := 0
  module.attack := Func("genshin_38").Bind(module)
  module.attackA := Func("genshin_37").Bind(module)
  module.attackB := Func("genshin_35").Bind(module)
  return module
}
genshin_40(module) {
  $.click.Call("left")
  setTacticDelay.Call(200, module.attack)
}
genshin_41(module) {
  module.attackA.Call()
}
genshin_42() {
  module := {}
  module.attack := Func("genshin_41").Bind(module)
  module.attackA := Func("genshin_40").Bind(module)
  return module
}
genshin_43(this) {
  for __index_for__, key in this.key {
    if ($.getState.Call(key)) {
      $.press.Call("" . (key) . ":up")
    }
  }
}
genshin_44(this, n) {
  pointStart := [client.width - 80, 0]
  pointEnd := [client.width, 80]
  point := $.findColor.Call(this.color[__ci_genshin__.Call(n)], pointStart, pointEnd)
  return point[1] * point[2] > 0
}
genshin_45(this, forced := false) {
  if (client.state.isSuspend) {
    return
  }
  if (!forced && $.now.Call() - this.ts.check <= 1000) {
    return
  }
  this.ts.check := $.now.Call()
  if !(this.findColor.Call(0)) {
    this.state.isVisible := true
    return
  }
  if ((this.findColor.Call(1)) || this.findColor.Call(2)) {
    this.state.isVisible := true
    return
  }
  this.state.isVisible := false
}
genshin_46(this) {
  this.state.current := ""
  this.state.isVisible := false
  $.press.Call("esc")
}
genshin_47(this, key) {
  this.state.current := key
  this.state.isVisible := true
  $.press.Call(key)
}
genshin_48(this, key) {
  this.checkVisibility.Call(true)
  if (this.state.isVisible) {
    $.press.Call("esc")
    if (key == this.state.current) {
      this.state.current := ""
      this.state.isVisible := false
      return
    }
    clearTimeout.Call(timer.closePaimon)
    timer.closePaimon := setTimeout.Call(Func("genshin_47").Bind(this, key), 800)
    return
  }
  this.state.current := key
  this.state.isVisible := true
  $.press.Call(key)
}
genshin_49(this) {
  for __index_for__, key in this.key {
    $.on.Call(key, Func("genshin_48").Bind(this, key))
    $.on.Call("esc", Func("genshin_46").Bind(this))
  }
}
genshin_50(time) {
  if !(config.data.easySkillTimer) {
    return
  }
  clearTimeout.Call(timer.countDown)
  timer.countDown := $.delay.Call(time, $.beep)
}
genshin_51(this, key, defaultValue := 1) {
  __array__ := $.split.Call(key, "/")
  __section__ := __array__[1]
  __key__ := __array__[2]
  IniRead, __result__, % this.source, % __section__, % __key__, % defaultValue
  return __result__
}
genshin_52(this) {
  setInterval.Call(this.check, 200)
}
genshin_53(this, level) {
  Process, Priority, % this.name, % level
}
genshin_54(this, isSuspend) {
  if (isSuspend) {
    if (this.state.isSuspend) {
      return
    }
    this.state.isSuspend := true
    $.suspend.Call(true)
    this.resetTimer.Call()
    this.resetKey.Call()
    return
  }
  if !(isSuspend) {
    if !(this.state.isSuspend) {
      return
    }
    this.state.isSuspend := false
    $.suspend.Call(false)
    return
  }
}
genshin_55(this) {
  for __key_for__, _timer in timer {
    clearTimeout.Call(_timer)
  }
}
genshin_56(this) {
  for __index_for__, key in ["middle", "right"] {
    if ($.getState.Call(key)) {
      $.click.Call("" . (key) . ":up")
    }
  }
  for __index_for__, key in ["alt", "ctrl", "e", "esc", "f", "space", "w", "x"] {
    if ($.getState.Call(key)) {
      $.press.Call("" . (key) . ":up")
    }
  }
  paimon.resetKey.Call()
}
genshin_57(this) {
  this.setPriority.Call("normal")
  this.resetTimer.Call()
  this.resetKey.Call()
}
genshin_58(this) {
  __array__ := $.getPosition.Call()
  x := __array__[1]
  y := __array__[2]
  if (x < 0) {
    return false
  }
  if (x > this.width) {
    return false
  }
  if (y < 0) {
    return false
  }
  if (y > this.height) {
    return false
  }
  return true
}
genshin_59(this) {
  return WinActive("ahk_exe " . (this.name) . "")
}
genshin_60(this) {
  name := "ahk_exe " . (this.name) . ""
  WinGetPos, __x__, __y__, __width__, __height__, % name
  return [__width__, __height__]
}
genshin_61(this) {
  Process, Close, % this.name
}
genshin_62(this) {
  if !(this.width) {
    size := this.getSize.Call()
    this.width := size[1]
    this.height := size[2]
  }
  if (!this.state.isSuspend && !(this.isActive.Call() && this.isInside.Call())) {
    this.setPriority.Call("low")
    this.suspend.Call(true)
    state.isAttacking := false
    return
  }
  if (this.state.isSuspend && (this.isActive.Call() && this.isInside.Call())) {
    this.setPriority.Call("normal")
    this.suspend.Call(false)
    return
  }
}
genshin_63(input) {
  if input is Number
    return input + 1
  return input
}
