# @ts-check

import '../../gis-static/lib/admin.ahk'
import '../../gis-static/lib/head.ahk'
import 'shell-ahk'

# declare
$ = $

# import

import './alice'
import './area'
import './buff'
import './camera'
import './character'
import './client'
import './color-manager'
import './config'
import './console'
import './controller'
import './cursor'
import './dashboard'
import './dictionary'
import './fishing'
import './gdip'
import './hud'
import './idle'
import './indicator'
import './jumper'
import './key-binding'
import './menu'
import './movement'
import './party'
import './party2'
import './picker'
import './point'
import './recorder'
import './replayer'
import './scene'
import './scene2'
import './skill'
import './sound'
import './tactic'
import './timer'
import './transparent'
import './upgrader'
import './window'

import './misc'